update aws role

diff --git a/.github/workflows/env.yaml b/.github/workflows/env.yaml
--- a/.github/workflows/env.yaml
+++ b/.github/workflows/env.yaml
@@ -1,10 +1,10 @@
-name: environment setup
+name: Backend deployment
 
 on:
   push:
-   branches:
-    - dev
-    - qa
+    branches:
+      - dev
+      - qa
   workflow_dispatch:
     inputs:
       branch:
@@ -14,28 +14,79 @@ on:
         type: choice
         options:
           - dev
-          - qa 
-        
+          - qa
+          - prod
+
+permissions:
+  id-token: write
+  contents: read
+
 jobs:
   set-environment:
     name: setup environments
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-20.04
     environment: ${{ github.ref_name || github.event.inputs.branch }}
     steps:
-      - name: Print environment name
-        run: |
-          echo "Deploying to the environment: ${{ github.ref_name || github.event.inputs.branch }}"
-
       - name: Set up environment
         run: |
-          echo "Deploying for the environment: ${{ github.ref_name || github.event.inputs.branch }}"
+          echo "Deploying for the environment: ${{ github.ref_name || github.event.inputs.branch }}"  
+    outputs:
+      image_tag: ${{ steps.docker.outputs.image_tag }}
 
-      - name: Display environment variables
-        run: |
-          echo "DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}"    # Example environment secret
-          echo "DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}"    # Example environment secret
+  docker-build-package:
+    name: Build and Package Maven Application
+    runs-on: ubuntu-20.04
+    needs: set-environment
 
-      - name: Use environment variables in deployment
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Set Up JDK 8
+        uses: actions/setup-java@v2
+        with:
+          java-version: '8'
+          distribution: 'adopt'
+          cache: maven
+      
+      - name: Build with Maven
+        run: mvn -B install --file pom.xml
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: ${{ secrets.ROLE_GITHUB }}
+          aws-region: ${{ vars.AWS_REGION }}
+
+      - name: Check if Docker is available and install if needed
         run: |
-          echo "Deploying to DOCKER_USERNAME: ${{ secrets.API_URL }}"
-          echo "Using DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}"
+          if ! command -v docker &> /dev/null; then
+            echo "Docker not found, installing..."
+            sudo apt-get update
+            sudo apt-get install -y \
+                apt-transport-https \
+                ca-certificates \
+                curl \
+                gnupg-agent \
+                software-properties-common
+            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
+            sudo add-apt-repository \
+              "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
+            sudo apt-get update
+            sudo apt-get install -y docker-ce docker-ce-cli containerd.io
+          else
+            echo "Docker is available, proceeding with the build."
+          fi
+
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v2
+
+      - name: Check AWS Credentials
+        run: aws sts get-caller-identity
+
+      - name: Build, Tag, and Push Docker Image to Amazon ECR
+        run: |
+          IMAGE_TAG=${{ github.run_number }}
+          docker build -t ${{ vars.BUILD_NAME }}:${IMAGE_TAG} ./
+          docker tag ${{ vars.BUILD_NAME }}:${IMAGE_TAG} ${{ vars.ECR_REPOSITORY }}/${{ vars.BUILD_NAME }}:${IMAGE_TAG}
+          docker push ${{ vars.ECR_REPOSITORY }}/${{ vars.BUILD_NAME }}:${IMAGE_TAG}
